# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  #vmImage: ubuntu-latest
  vmImage: 'vs2017-win2016'
strategy:
  matrix:
    Python36:
      python.version: '3.6'


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install requests
    pip install selenium
    pip install html-testRunner
  displayName: 'Install dependencies'
  
 # Running test for print numbers
- script: |
      cd print_numbers/tst && python print_number_test.py
  displayName: 'Running test for print numbers'   

# Running test for area of traingle
- script: |
      cd area_of_traingle/tst && python area_of_traingle_test.py
  displayName: 'Running test for area of traingle'
 
  # Running test for https://github.com/phil-rice/datakata.git
- script: |
      cd phil_rice_datakata/tst && python foot_ball_team_test.py
  displayName: 'Running test for phil-rice/datakata'
    
 # Running test for hcl web tests
- script: |      
      cp "%ChromeWebDriver%"/chromedriver.exe hcl_portal/WebDrivers/
      cd hcl_portal && python RunTestSuite.py
  displayName: 'Running test for hcl web tests'

- task: PublishTestResults@1
    inputs:
      testResultsFiles: 'hcl_portal/TestReport/*.html'
      testRunTitle: '$(Agent.OS) - $(Build.DefinitionName) - Python $(python.version)'
    condition: succeededOrFailed()

- task: PublishTestResults@2
    inputs:
      testResultsFiles: 'phil_rice_datakata/tst/tst_report/*.html'
      testRunTitle: '$(Agent.OS) - $(Build.DefinitionName) - Python $(python.version) - phil_rice_datakata'
    condition: succeededOrFailed()

- task: PublishTestResults@3
    inputs:
      testResultsFiles: 'area_of_traingle/tst/tst_report/*.html'
      testRunTitle: '$(Agent.OS) - $(Build.DefinitionName) - Python $(python.version) - area_of_traingle'
    condition: succeededOrFailed()

- task: PublishTestResults@4
    inputs:
      testResultsFiles: 'print_numbers/tst/tst_report/*.html'
      testRunTitle: '$(Agent.OS) - $(Build.DefinitionName) - Python $(python.version) - area_of_traingle'
    condition: succeededOrFailed()
